# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
  statsd:
    image: jaconel/statsd
    restart: always
    ports:
      - "8125:8125"
      - "8126:8126"


